In [2]:
import pandas as pd

# Set the file path (use raw string to avoid backslash issues)
file_path = r"C:\Users\Neg\RNA_seq_python_GC\tcga_stad_counts.tsv.gz"

# Load the compressed TSV file
counts_df = pd.read_csv(file_path, sep='\t', compression='gzip', index_col=0)

# Display the first few rows
counts_df.head()

,TCGA-BR-6457-01A,TCGA-BR-6457-11A,TCGA-RD-A7BT-01A,TCGA-CD-8530-01A,TCGA-HU-A4H4-01A,TCGA-FP-A4BF-01A,TCGA-CG-5724-01A,TCGA-F1-6874-01A,TCGA-D7-6820-01A,TCGA-CG-5728-11A,...,TCGA-VQ-A8PD-01A,TCGA-HJ-7597-01A,TCGA-BR-8361-01A,TCGA-IN-7806-01A,TCGA-BR-4201-01A,TCGA-CG-4436-01A,TCGA-BR-A4CR-01A,TCGA-3M-AB47-01A,TCGA-BR-A4QI-01A,TCGA-CG-4440-01A
Ensembl_ID,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003.15,10.613789,9.995767,12.845490,10.828930,10.906139,12.515946,10.743151,9.566054,9.060696,8.577429,...,10.643856,10.162391,9.586840,10.959278,11.667112,13.072468,11.745674,11.547377,14.116912,9.761551
ENSG00000000005.6,2.321928,2.000000,1.584963,1.000000,0.000000,3.906891,3.321928,0.000000,1.584963,1.000000,...,1.000000,2.584963,0.000000,0.000000,1.584963,1.584963,1.000000,1.584963,0.000000,0.000000
ENSG00000000419.13,10.309476,9.501837,12.627306,11.278449,12.514221,12.765493,11.340406,10.883407,11.758223,8.832890,...,10.949827,11.258566,11.138272,11.514221,12.072803,12.853505,12.079485,10.932215,12.829128,12.155451
ENSG00000000457.14,8.816984,8.622052,9.724514,10.092757,10.589651,9.693487,8.330917,9.861087,10.597121,7.982994,...,10.424166,10.556506,10.127994,10.567956,9.923327,9.774787,10.358651,9.515700,10.893302,9.946906
ENSG00000000460.17,7.149747,6.022368,10.179909,8.829723,9.548822,9.005625,8.169925,9.036174,9.131857,5.977280,...,8.985842,9.238405,9.129283,8.965784,9.264443,10.217958,10.303781,7.870365,9.663558,9.902375

In [4]:
# Save a backup copy
counts_df.to_csv(r"C:\Users\Neg\RNA_seq_python_GC\raw_counts_backup.csv")

In [6]:
import pandas as pd

# Load the raw count data
file_path = r"C:\Users\Neg\RNA_seq_python_GC\tcga_stad_counts.tsv.gz"
counts_df = pd.read_csv(file_path, sep='\t', compression='gzip', index_col=0)

# Display a preview
counts_df.head()

# Save a backup copy
counts_df.to_csv(r"C:\Users\Neg\RNA_seq_python_GC\raw_counts_backup.csv")

In [8]:
import pandas as pd

# ✅ Local path to raw counts CSV file
file_path = r"C:\Users\Neg\RNA_seq_python_GC\raw_counts_backup.csv"

# ✅ Load raw counts
counts_df = pd.read_csv(file_path, index_col=0)

# ✅ Filter genes with count >1 in at least 5 samples
filtered_df = counts_df[counts_df.gt(1).sum(axis=1) >= 5]

# ✅ Save filtered data
filtered_path = r"C:\Users\Neg\RNA_seq_python_GC\filtered_counts.csv"
filtered_df.to_csv(filtered_path)

# ✅ Preview
print("Filtered count matrix shape:", filtered_df.shape)
filtered_df.head()

Filtered count matrix shape: (56678, 448)

,TCGA-BR-6457-01A,TCGA-BR-6457-11A,TCGA-RD-A7BT-01A,TCGA-CD-8530-01A,TCGA-HU-A4H4-01A,TCGA-FP-A4BF-01A,TCGA-CG-5724-01A,TCGA-F1-6874-01A,TCGA-D7-6820-01A,TCGA-CG-5728-11A,...,TCGA-VQ-A8PD-01A,TCGA-HJ-7597-01A,TCGA-BR-8361-01A,TCGA-IN-7806-01A,TCGA-BR-4201-01A,TCGA-CG-4436-01A,TCGA-BR-A4CR-01A,TCGA-3M-AB47-01A,TCGA-BR-A4QI-01A,TCGA-CG-4440-01A
Ensembl_ID,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003.15,10.613789,9.995767,12.845490,10.828930,10.906139,12.515946,10.743151,9.566054,9.060696,8.577429,...,10.643856,10.162391,9.586840,10.959278,11.667112,13.072468,11.745674,11.547377,14.116912,9.761551
ENSG00000000005.6,2.321928,2.000000,1.584963,1.000000,0.000000,3.906891,3.321928,0.000000,1.584963,1.000000,...,1.000000,2.584963,0.000000,0.000000,1.584963,1.584963,1.000000,1.584963,0.000000,0.000000
ENSG00000000419.13,10.309476,9.501837,12.627306,11.278449,12.514221,12.765493,11.340406,10.883407,11.758223,8.832890,...,10.949827,11.258566,11.138272,11.514221,12.072803,12.853505,12.079485,10.932215,12.829128,12.155451
ENSG00000000457.14,8.816984,8.622052,9.724514,10.092757,10.589651,9.693487,8.330917,9.861087,10.597121,7.982994,...,10.424166,10.556506,10.127994,10.567956,9.923327,9.774787,10.358651,9.515700,10.893302,9.946906
ENSG00000000460.17,7.149747,6.022368,10.179909,8.829723,9.548822,9.005625,8.169925,9.036174,9.131857,5.977280,...,8.985842,9.238405,9.129283,8.965784,9.264443,10.217958,10.303781,7.870365,9.663558,9.902375

In [10]:
import pandas as pd
import numpy as np

# Load filtered count matrix
filtered_path = r"C:\Users\Neg\RNA_seq_python_GC\filtered_counts.csv"
filtered_df = pd.read_csv(filtered_path, index_col=0)

# Apply log2 transformation with pseudocount
log2_df = np.log2(filtered_df + 1)

# Save the log2 normalized data
log2_path = r"C:\Users\Neg\RNA_seq_python_GC\log2_normalized_counts.csv"
log2_df.to_csv(log2_path)

# Preview
log2_df.head()

,TCGA-BR-6457-01A,TCGA-BR-6457-11A,TCGA-RD-A7BT-01A,TCGA-CD-8530-01A,TCGA-HU-A4H4-01A,TCGA-FP-A4BF-01A,TCGA-CG-5724-01A,TCGA-F1-6874-01A,TCGA-D7-6820-01A,TCGA-CG-5728-11A,...,TCGA-VQ-A8PD-01A,TCGA-HJ-7597-01A,TCGA-BR-8361-01A,TCGA-IN-7806-01A,TCGA-BR-4201-01A,TCGA-CG-4436-01A,TCGA-BR-A4CR-01A,TCGA-3M-AB47-01A,TCGA-BR-A4QI-01A,TCGA-CG-4440-01A
Ensembl_ID,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003.15,3.537767,3.458876,3.791344,3.564248,3.573634,3.756591,3.553748,3.401365,3.330658,3.259638,...,3.541497,3.480574,3.404200,3.580058,3.663016,3.814803,3.671936,3.649314,3.918092,3.427814
ENSG00000000005.6,1.732021,1.584963,1.370143,1.000000,0.000000,2.294809,2.111675,0.000000,1.370143,1.000000,...,1.000000,1.841958,0.000000,0.000000,1.370143,1.370143,1.000000,1.370143,0.000000,0.000000
ENSG00000000419.13,3.499460,3.392570,3.768428,3.618056,3.756406,3.782984,3.625318,3.570877,3.673356,3.297616,...,3.578918,3.615718,3.601491,3.645497,3.708497,3.792179,3.709234,3.576790,3.789638,3.717589
ENSG00000000457.14,3.295280,3.266345,3.422840,3.471546,3.534765,3.418660,3.222019,3.441097,3.535695,3.167196,...,3.514017,3.530633,3.476122,3.532062,3.449340,3.429587,3.505720,3.394473,3.572077,3.452451
ENSG00000000460.17,3.026755,2.811958,3.482837,3.297151,3.399010,3.322739,3.196910,3.327137,3.340827,2.802665,...,3.319884,3.355919,3.340460,3.316983,3.359583,3.487738,3.498733,3.148993,3.414617,3.446571