In [2]:
import pandas as pd

# Load the filtered expression matrix (matching clinical samples)
expr_path = r"C:\Users\Neg\RNA_seq_python_GC\expression_matched.csv"
expr_df = pd.read_csv(expr_path, index_col=0)

# Show shape and preview
print("Expression matrix shape:", expr_df.shape)
expr_df.iloc[:5, :5]  # show first 5 genes and 5 samples

Expression matrix shape: (56678, 448)

,TCGA-VQ-A8PP-01,TCGA-HU-A4H6-01,TCGA-MX-A5UG-01,TCGA-BR-8077-01,TCGA-CG-5720-01
Ensembl_ID,,,,,
ENSG00000000003.15,10.731319,11.339850,11.294046,13.200439,11.009129
ENSG00000000005.6,0.000000,0.000000,2.321928,0.000000,1.584963
ENSG00000000419.13,10.871135,12.141469,10.924813,12.038919,10.906139
ENSG00000000457.14,10.100662,10.306062,10.535275,9.552669,8.968667
ENSG00000000460.17,9.025140,9.388017,8.921841,8.758223,8.330917

In [3]:
# Extract sample types from TCGA barcodes
sample_types = expr_df.columns.str.slice(13, 15)

# Create a group label Series
sample_labels = sample_types.map({'01': 'Tumor', '11': 'Normal'})

# Show value counts
print("Sample group counts:")
print(sample_labels.value_counts())

Sample group counts:
Tumor     412
Normal     36
Name: count, dtype: int64

In [4]:
# Load clinical and expression files
clinical = pd.read_csv(r"C:\Users\Neg\RNA_seq_python_GC\clinical_cleaned.csv")
expr = pd.read_csv(r"C:\Users\Neg\RNA_seq_python_GC\filtered_counts.csv", index_col=0)

# Keep original column names for matching
common_ids = list(set(clinical['sample_id']) & set(expr.columns))

# Subset both datasets
expr_matched = expr[common_ids].copy()
clinical_matched = clinical[clinical['sample_id'].isin(common_ids)].copy()

# Now standardize sample barcodes in expr_matched
expr_matched.columns = expr_matched.columns.str.slice(0, 15)

# Save the matched files
expr_matched.to_csv(r"C:\Users\Neg\RNA_seq_python_GC\expression_matched.csv")
clinical_matched.to_csv(r"C:\Users\Neg\RNA_seq_python_GC\clinical_matched.csv", index=False)

print("✅ Fixed and saved matched expression and clinical files.")

✅ Fixed and saved matched expression and clinical files.

In [7]:
import pandas as pd

# Load the matched expression data
expr_df = pd.read_csv(r"C:\Users\Neg\RNA_seq_python_GC\expression_matched.csv", index_col=0)

# Preview shape and column names
print("Expression matrix shape:", expr_df.shape)
expr_df.iloc[:5, :5]  # first 5 genes x 5 samples

Expression matrix shape: (56678, 448)

,TCGA-BR-A4QM-01,TCGA-VQ-A8PP-01,TCGA-VQ-AA6I-01,TCGA-BR-A4PD-01,TCGA-VQ-A8PH-01
Ensembl_ID,,,,,
ENSG00000000003.15,10.700440,10.731319,10.427313,10.310613,12.659550
ENSG00000000005.6,0.000000,0.000000,2.321928,0.000000,1.000000
ENSG00000000419.13,10.663558,10.871135,11.401946,13.305634,12.694358
ENSG00000000457.14,8.459432,10.100662,10.766529,10.105909,9.287712
ENSG00000000460.17,6.584963,9.025140,10.283088,9.552669,9.467606

In [8]:
# Extract sample type from barcode (13–15 characters)
sample_types = expr_df.columns.str.slice(13, 15)

# Create tumor/normal group labels
sample_labels = sample_types.map({'01': 'Tumor', '11': 'Normal'})

# Check distribution
print("Sample group counts:")
print(sample_labels.value_counts())

Sample group counts:
Tumor     412
Normal     36
Name: count, dtype: int64

In [14]:
pip install rpy2

Requirement already satisfied: rpy2 in c:\users\neg\anaconda3\lib\site-packages (3.5.17)
Requirement already satisfied: cffi>=1.15.1 in c:\users\neg\anaconda3\lib\site-packages (from rpy2) (1.17.1)
Requirement already satisfied: jinja2 in c:\users\neg\anaconda3\lib\site-packages (from rpy2) (3.1.4)
Requirement already satisfied: tzlocal in c:\users\neg\anaconda3\lib\site-packages (from rpy2) (5.3.1)
Requirement already satisfied: packaging in c:\users\neg\anaconda3\lib\site-packages (from rpy2) (24.1)
Requirement already satisfied: pycparser in c:\users\neg\anaconda3\lib\site-packages (from cffi>=1.15.1->rpy2) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\neg\anaconda3\lib\site-packages (from jinja2->rpy2) (2.1.3)
Requirement already satisfied: tzdata in c:\users\neg\anaconda3\lib\site-packages (from tzlocal->rpy2) (2023.3)
Note: you may need to restart the kernel to use updated packages.

In [11]:
%load_ext rpy2.ipython

C:\Users\Neg\anaconda3\Lib\site-packages\rpy2\robjects\packages.py:367: UserWarning: The symbol 'quartz' is not in this R namespace/package.
  warnings.warn(

In [12]:
%load_ext rpy2.ipython

%%R
R.version.string  # This will confirm your R setup

C:\Users\Neg\anaconda3\Lib\site-packages\rpy2\robjects\packages.py:367: UserWarning: The symbol 'quartz' is not in this R namespace/package.
  warnings.warn(
UsageError: Line magic function `%%R` not found.

In [13]:
%%R
R.version.string
S

[1] "R version 4.0.2 (2020-06-22)"

In [15]:
%%R
if (!requireNamespace("DESeq2", quietly = TRUE)) {
    install.packages("BiocManager")
    BiocManager::install("DESeq2")
}
library(DESeq2)

--- Please select a CRAN mirror for use in this session ---

  There is a binary version available but the source version is later:
             binary  source needs_compilation
BiocManager 1.30.16 1.30.25             FALSE

Update all/some/none? [a/s/n]:

 n

Installing package into 'C:/Users/Neg/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)
installing the source package 'BiocManager'

trying URL 'https://cloud.r-project.org/src/contrib/BiocManager_1.30.25.tar.gz'
Content type 'application/x-gzip' length 593414 bytes (579 KB)
downloaded 579 KB


The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages'
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.12 (BiocManager 1.30.25), R 4.0.2 (2020-06-22)
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.0.2/library
  packages:
    boot, class, cluster, codetools, foreign, KernSmooth, lattice, mgcv, nlme,
    nnet, rpart, spatial, survival
Old packages: 'affy', 'affyio', 'annotate', 'AnnotationDbi', 'askpass',
  'backports', 'BH', 'Biobase', 'BiocFileCache', 'BiocGenerics',
  'BiocParallel', 'biomaRt', 'Biostrings', 'bit', 'bit64', 'bitops', 'blob',
  'brio', 'cachem', 'cli', 'colorspace', 'covr', 'cpp11', 'crayon',
  'data.table', 'DBI', 'dbplyr', 'DelayedArray', 'digest', 'ellipsis',
  'evaluate', 'fansi', 'farver', 'fastmap', 'fontawesome', 'formatR', 'fs',
  'gcrma', 'genefilter', 'generics', 'GenomeInfoDb', 'GenomeInfoDbData',
  'GenomicAlignments', 'GenomicFeatures', 'GenomicRanges', 'haven', 'hms',
  'htmltools', 'httr', 'IRanges', 'isoband', 'jsonlite', 'lifecycle', 'limma',
  'lubridate', 'magrittr', 'matrixStats', 'mime', 'openssl', 'org.Hs.eg.db',
  'pillar', 'preprocessCore', 'prettyunits', 'processx', 'progress', 'ps',
  'purrr', 'R6', 'ragg', 'rappdirs', 'RcppArmadillo', 'RCurl', 'readr',
  'readxl', 'Rhtslib', 'Rsamtools', 'RSQLite', 'rtracklayer', 'S4Vectors',
  'sass', 'scales', 'simpleaffy', 'snow', 'stringr', 'SummarizedExperiment',
  'sys', 'systemfonts', 'testthat', 'textshaping', 'tidyr', 'tidyselect',
  'timechange', 'tinytex', 'tzdb', 'utf8', 'uuid', 'vctrs', 'vroom', 'waldo',
  'withr', 'xfun', 'XML', 'xml2', 'XVector', 'yaml', 'zlibbioc'
Loading required package: S4Vectors
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min


Attaching package: 'S4Vectors'

The following object is masked from 'package:base':

    expand.grid

Loading required package: IRanges

Attaching package: 'IRanges'

The following object is masked from 'package:grDevices':

    windows

Loading required package: GenomicRanges
Loading required package: GenomeInfoDb
Loading required package: SummarizedExperiment
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: 'matrixStats'

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians


Attaching package: 'DelayedArray'

The following objects are masked from 'package:matrixStats':

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from 'package:base':

    aperm, apply, rowsum

Error: package or namespace load failed for 'DESeq2' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 object 'pkgInfo' not found
In addition: Warning messages:
1: In loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  package 'Rcpp' has no 'package.rds' in Meta/
2: package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'DESeq2'
3: package 'DESeq2' was built under R version 4.0.3
4: In loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  package 'Rcpp' has no 'package.rds' in Meta/
Error: package or namespace load failed for 'DESeq2' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 object 'pkgInfo' not found

RInterpreterError: Failed to parse and evaluate line 'if (!requireNamespace("DESeq2", quietly = TRUE)) {\n    install.packages("BiocManager")\n    BiocManager::install("DESeq2")\n}\nlibrary(DESeq2)\n'.
R error message: "Error: package or namespace load failed for 'DESeq2' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):\n object 'pkgInfo' not found"
R stdout:
Installing package into 'C:/Users/Neg/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)
installing the source package 'BiocManager'

trying URL 'https://cloud.r-project.org/src/contrib/BiocManager_1.30.25.tar.gz'
Content type 'application/x-gzip' length 593414 bytes (579 KB)
downloaded 579 KB


The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages'
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.12 (BiocManager 1.30.25), R 4.0.2 (2020-06-22)
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.0.2/library
  packages:
    boot, class, cluster, codetools, foreign, KernSmooth, lattice, mgcv, nlme,
    nnet, rpart, spatial, survival
Old packages: 'affy', 'affyio', 'annotate', 'AnnotationDbi', 'askpass',
  'backports', 'BH', 'Biobase', 'BiocFileCache', 'BiocGenerics',
  'BiocParallel', 'biomaRt', 'Biostrings', 'bit', 'bit64', 'bitops', 'blob',
  'brio', 'cachem', 'cli', 'colorspace', 'covr', 'cpp11', 'crayon',
  'data.table', 'DBI', 'dbplyr', 'DelayedArray', 'digest', 'ellipsis',
  'evaluate', 'fansi', 'farver', 'fastmap', 'fontawesome', 'formatR', 'fs',
  'gcrma', 'genefilter', 'generics', 'GenomeInfoDb', 'GenomeInfoDbData',
  'GenomicAlignments', 'GenomicFeatures', 'GenomicRanges', 'haven', 'hms',
  'htmltools', 'httr', 'IRanges', 'isoband', 'jsonlite', 'lifecycle', 'limma',
  'lubridate', 'magrittr', 'matrixStats', 'mime', 'openssl', 'org.Hs.eg.db',
  'pillar', 'preprocessCore', 'prettyunits', 'processx', 'progress', 'ps',
  'purrr', 'R6', 'ragg', 'rappdirs', 'RcppArmadillo', 'RCurl', 'readr',
  'readxl', 'Rhtslib', 'Rsamtools', 'RSQLite', 'rtracklayer', 'S4Vectors',
  'sass', 'scales', 'simpleaffy', 'snow', 'stringr', 'SummarizedExperiment',
  'sys', 'systemfonts', 'testthat', 'textshaping', 'tidyr', 'tidyselect',
  'timechange', 'tinytex', 'tzdb', 'utf8', 'uuid', 'vctrs', 'vroom', 'waldo',
  'withr', 'xfun', 'XML', 'xml2', 'XVector', 'yaml', 'zlibbioc'
Loading required package: S4Vectors
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min


Attaching package: 'S4Vectors'

The following object is masked from 'package:base':

    expand.grid

Loading required package: IRanges

Attaching package: 'IRanges'

The following object is masked from 'package:grDevices':

    windows

Loading required package: GenomicRanges
Loading required package: GenomeInfoDb
Loading required package: SummarizedExperiment
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: 'matrixStats'

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians


Attaching package: 'DelayedArray'

The following objects are masked from 'package:matrixStats':

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from 'package:base':

    aperm, apply, rowsum

Error: package or namespace load failed for 'DESeq2' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 object 'pkgInfo' not found
In addition: Warning messages:
1: In loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  package 'Rcpp' has no 'package.rds' in Meta/
2: package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'DESeq2'
3: package 'DESeq2' was built under R version 4.0.3
4: In loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  package 'Rcpp' has no 'package.rds' in Meta/

In [17]:
%%R
install.packages("Rcpp", dependencies = TRUE, force = TRUE)

  There are binary versions available but the source versions are later:
           binary source needs_compilation
tinytest    1.3.1  1.4.1             FALSE
inline     0.3.19 0.3.21             FALSE
pkgKitten   0.2.2  0.2.4             FALSE
Rcpp      1.0.8.3 1.0.14              TRUE

  Binaries will be installed
package 'rbenchmark' successfully unpacked and MD5 sums checked
package 'Rcpp' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages

Installing package into 'C:/Users/Neg/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)
also installing the dependencies 'tinytest', 'inline', 'rbenchmark', 'pkgKitten'

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rbenchmark_1.0.0.zip'
Content type 'application/zip' length 22292 bytes (21 KB)
downloaded 21 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/Rcpp_1.0.8.3.zip'
Content type 'application/zip' length 3354808 bytes (3.2 MB)
downloaded 3.2 MB

installing the source packages 'tinytest', 'inline', 'pkgKitten'

trying URL 'https://cloud.r-project.org/src/contrib/tinytest_1.4.1.tar.gz'
Content type 'application/x-gzip' length 587352 bytes (573 KB)
downloaded 573 KB

trying URL 'https://cloud.r-project.org/src/contrib/inline_0.3.21.tar.gz'
Content type 'application/x-gzip' length 25454 bytes (24 KB)
downloaded 24 KB

trying URL 'https://cloud.r-project.org/src/contrib/pkgKitten_0.2.4.tar.gz'
Content type 'application/x-gzip' length 11381 bytes (11 KB)
downloaded 11 KB


The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages'

In [19]:
%%R
BiocManager::install("DESeq2", force = TRUE)

  There are binary versions available but the source versions are later:
          binary source needs_compilation
lifecycle  1.0.1  1.0.4             FALSE
pillar     1.7.0 1.10.2             FALSE
cli        3.2.0  3.6.4              TRUE
glue       1.6.2  1.8.0              TRUE
gtable     0.3.0  0.3.6             FALSE
rlang      1.0.2  1.1.6              TRUE
scales     1.2.0  1.3.0              TRUE
tibble     3.1.6  3.2.1              TRUE
vctrs      0.4.1  0.6.5              TRUE
ggplot2    3.3.5  3.5.2             FALSE

  Binaries will be installed
package 'cli' successfully unpacked and MD5 sums checked
package 'glue' successfully unpacked and MD5 sums checked
package 'rlang' successfully unpacked and MD5 sums checked
package 'scales' successfully unpacked and MD5 sums checked
package 'tibble' successfully unpacked and MD5 sums checked
package 'vctrs' successfully unpacked and MD5 sums checked
package 'DESeq2' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages
Update all/some/none? [a/s/n]:

 n

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.12 (BiocManager 1.30.25), R 4.0.2 (2020-06-22)
Installing package(s) 'DESeq2'
Warning: dependency 'locfit' is not available
also installing the dependencies 'lifecycle', 'pillar', 'cli', 'glue', 'gtable', 'rlang', 'scales', 'tibble', 'vctrs', 'ggplot2'

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cli_3.2.0.zip'
Content type 'application/zip' length 1255499 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/glue_1.6.2.zip'
Content type 'application/zip' length 171950 bytes (167 KB)
downloaded 167 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rlang_1.0.2.zip'
Content type 'application/zip' length 1718546 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/scales_1.2.0.zip'
Content type 'application/zip' length 616764 bytes (602 KB)
downloaded 602 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/tibble_3.1.6.zip'
Content type 'application/zip' length 872395 bytes (851 KB)
downloaded 851 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/vctrs_0.4.1.zip'
Content type 'application/zip' length 1569486 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/DESeq2_1.30.1.zip'
Content type 'application/zip' length 2863628 bytes (2.7 MB)
downloaded 2.7 MB

installing the source packages 'lifecycle', 'pillar', 'gtable', 'ggplot2'

trying URL 'https://cloud.r-project.org/src/contrib/lifecycle_1.0.4.tar.gz'
Content type 'application/x-gzip' length 107656 bytes (105 KB)
downloaded 105 KB

trying URL 'https://cloud.r-project.org/src/contrib/pillar_1.10.2.tar.gz'
Content type 'application/x-gzip' length 408422 bytes (398 KB)
downloaded 398 KB

trying URL 'https://cloud.r-project.org/src/contrib/gtable_0.3.6.tar.gz'
Content type 'application/x-gzip' length 148148 bytes (144 KB)
downloaded 144 KB

trying URL 'https://cloud.r-project.org/src/contrib/ggplot2_3.5.2.tar.gz'
Content type 'application/x-gzip' length 3580451 bytes (3.4 MB)
downloaded 3.4 MB


The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages'
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.0.2/library
  packages:
    boot, class, cluster, codetools, foreign, KernSmooth, lattice, mgcv, nlme,
    nnet, rpart, spatial, survival
Old packages: 'affy', 'affyio', 'annotate', 'AnnotationDbi', 'askpass',
  'backports', 'BH', 'Biobase', 'BiocFileCache', 'BiocGenerics',
  'BiocParallel', 'biomaRt', 'Biostrings', 'bit', 'bit64', 'bitops', 'blob',
  'brio', 'cachem', 'cli', 'colorspace', 'covr', 'cpp11', 'crayon',
  'data.table', 'DBI', 'dbplyr', 'DelayedArray', 'digest', 'ellipsis',
  'evaluate', 'fansi', 'farver', 'fastmap', 'fontawesome', 'formatR', 'fs',
  'gcrma', 'genefilter', 'generics', 'GenomeInfoDb', 'GenomeInfoDbData',
  'GenomicAlignments', 'GenomicFeatures', 'GenomicRanges', 'glue', 'haven',
  'hms', 'htmltools', 'httr', 'IRanges', 'isoband', 'jsonlite', 'lifecycle',
  'limma', 'lubridate', 'magrittr', 'matrixStats', 'mime', 'openssl',
  'org.Hs.eg.db', 'pillar', 'preprocessCore', 'prettyunits', 'processx',
  'progress', 'ps', 'purrr', 'R6', 'ragg', 'rappdirs', 'Rcpp', 'RcppArmadillo',
  'RCurl', 'readr', 'readxl', 'Rhtslib', 'rlang', 'Rsamtools', 'RSQLite',
  'rtracklayer', 'S4Vectors', 'sass', 'scales', 'simpleaffy', 'snow',
  'stringr', 'SummarizedExperiment', 'sys', 'systemfonts', 'testthat',
  'textshaping', 'tibble', 'tidyr', 'tidyselect', 'timechange', 'tinytex',
  'tzdb', 'utf8', 'uuid', 'vctrs', 'vroom', 'waldo', 'withr', 'xfun', 'XML',
  'xml2', 'XVector', 'yaml', 'zlibbioc'
In addition: Warning messages:
1: In install.packages(...) :
  installation of package 'lifecycle' had non-zero exit status
2: In install.packages(...) :
  installation of package 'pillar' had non-zero exit status
3: In install.packages(...) :
  installation of package 'gtable' had non-zero exit status
4: In install.packages(...) :
  installation of package 'ggplot2' had non-zero exit status

In [21]:
%%R
library(DESeq2)

The package `ellipsis` (>= 0.3.2) is required as of rlang 1.0.0.
! Would you like to update it now?
  You will likely need to restart R if you update now.
i Not updating now is completely safe and will only cause import warnings.

1: Yes
2: No

Selection:  1

package 'ellipsis' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages
Installing package into 'C:/Users/Neg/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/ellipsis_0.3.2.zip'
Content type 'application/zip' length 48927 bytes (47 KB)
downloaded 47 KB

Error: package or namespace load failed for 'DESeq2' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 object 'pkgInfo' not found
In addition: Warning messages:
1: package 'DESeq2' was built under R version 4.0.3
2: In loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  package 'memoise' has no 'package.rds' in Meta/
Error: package or namespace load failed for 'DESeq2' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 object 'pkgInfo' not found

RInterpreterError: Failed to parse and evaluate line 'library(DESeq2)\n'.
R error message: "Error: package or namespace load failed for 'DESeq2' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):\n object 'pkgInfo' not found"
R stdout:
Installing package into 'C:/Users/Neg/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/ellipsis_0.3.2.zip'
Content type 'application/zip' length 48927 bytes (47 KB)
downloaded 47 KB

Error: package or namespace load failed for 'DESeq2' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 object 'pkgInfo' not found
In addition: Warning messages:
1: package 'DESeq2' was built under R version 4.0.3
2: In loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  package 'memoise' has no 'package.rds' in Meta/

In [23]:
%%R
install.packages("BiocManager", repos = "https://cloud.r-project.org")
BiocManager::install("DESeq2", force = TRUE)

  There is a binary version available but the source version is later:
             binary  source needs_compilation
BiocManager 1.30.16 1.30.25             FALSE


  There are binary versions available but the source versions are later:
          binary source needs_compilation
cli        3.2.0  3.6.4              TRUE
lifecycle  1.0.1  1.0.4             FALSE
gtable     0.3.0  0.3.6             FALSE
rlang      1.0.2  1.1.6              TRUE
scales     1.2.0  1.3.0              TRUE
vctrs      0.4.1  0.6.5              TRUE
ggplot2    3.3.5  3.5.2             FALSE

  Binaries will be installed
package 'cli' successfully unpacked and MD5 sums checked
package 'rlang' successfully unpacked and MD5 sums checked
package 'scales' successfully unpacked and MD5 sums checked
package 'vctrs' successfully unpacked and MD5 sums checked
package 'DESeq2' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages
Update all/some/none? [a/s/n]:

 a

  There are binary versions available but the source versions are later:
                  binary    source needs_compilation
pkgbuild           1.3.1     1.4.7             FALSE
dplyr              1.0.8     1.1.4              TRUE
curl               4.3.2     6.2.2              TRUE
stringi            1.7.6     1.8.7              TRUE
callr              3.7.0     3.7.6             FALSE
pkgload            1.2.4     1.4.0             FALSE
askpass              1.1     1.2.1              TRUE
backports          1.4.1     1.5.0              TRUE
BH              1.78.0-0  1.87.0-1             FALSE
bit                4.0.4     4.6.0              TRUE
bit64              4.0.5   4.6.0-1              TRUE
bitops             1.0-7     1.0-9              TRUE
blob               1.2.3     1.2.4             FALSE
brio               1.1.3     1.1.5              TRUE
cachem             1.0.6     1.1.0              TRUE
cli                3.2.0     3.6.4              TRUE
colorspace         2.0-3     2.1-1              TRUE
covr               3.5.1     3.6.4              TRUE
cpp11              0.4.2     0.5.2             FALSE
crayon             1.5.1     1.5.3             FALSE
data.table        1.14.2    1.17.0              TRUE
DBI                1.1.2     1.2.3             FALSE
dbplyr             2.1.1     2.5.0             FALSE
digest            0.6.29    0.6.37              TRUE
evaluate            0.15     1.0.3             FALSE
fansi              1.0.3     1.0.6              TRUE
farver             2.1.0     2.1.2              TRUE
fastmap            1.1.0     1.2.0              TRUE
fontawesome        0.2.2     0.5.3             FALSE
formatR             1.12      1.14             FALSE
fs                 1.5.2     1.6.6              TRUE
generics           0.1.2     0.1.3             FALSE
glue               1.6.2     1.8.0              TRUE
haven              2.5.0     2.5.4              TRUE
hms                1.1.1     1.1.3             FALSE
htmltools          0.5.2   0.5.8.1              TRUE
httr               1.4.2     1.4.7             FALSE
isoband            0.2.5     0.2.7              TRUE
jsonlite           1.8.0     2.0.0              TRUE
lifecycle          1.0.1     1.0.4             FALSE
lubridate          1.8.0     1.9.4              TRUE
mime                0.12      0.13              TRUE
openssl            2.0.0     2.3.2              TRUE
pillar             1.7.0    1.10.2             FALSE
prettyunits        1.1.1     1.2.0             FALSE
processx           3.5.3     3.8.6              TRUE
progress           1.2.2     1.2.3             FALSE
ps                 1.6.0     1.9.1              TRUE
purrr              0.3.4     1.0.4              TRUE
R6                 2.5.1     2.6.1             FALSE
ragg               1.2.2     1.4.0              TRUE
Rcpp             1.0.8.3    1.0.14              TRUE
RcppArmadillo 0.11.0.0.0  14.4.1-1              TRUE
RCurl           1.98-1.6 1.98-1.17              TRUE
readr              2.1.2     2.1.5              TRUE
readxl             1.4.0     1.4.5              TRUE
rlang              1.0.2     1.1.6              TRUE
RSQLite           2.2.12     2.3.9              TRUE
rtracklayer       1.49.5    1.50.0              TRUE
sass               0.4.1    0.4.10              TRUE
scales             1.2.0     1.3.0              TRUE
stringr            1.4.0     1.5.1             FALSE
sys                  3.4     3.4.3              TRUE
systemfonts        1.0.4     1.2.2              TRUE
testthat           3.1.3     3.2.3              TRUE
textshaping        0.3.6     1.0.0              TRUE
tibble             3.1.6     3.2.1              TRUE
tidyr              1.2.0     1.3.1              TRUE
tidyselect         1.1.2     1.2.1              TRUE
timechange         0.0.2     0.3.0              TRUE
tinytex             0.38      0.57             FALSE
tzdb               0.3.0     0.5.0              TRUE
utf8               1.2.2     1.2.4              TRUE
uuid               1.1-0     1.2-1              TRUE
vctrs              0.4.1     0.6.5              TRUE
vroom              1.5.7     1.6.5              TRUE
waldo              0.4.0     0.6.1             FALSE
withr              2.5.0     3.0.2             FALSE
xfun                0.30      0.52              TRUE
XML             3.99-0.9 3.99-0.18              TRUE
xml2               1.3.3     1.3.8              TRUE
yaml               2.3.5    2.3.10              TRUE

  Binaries will be installed
package 'dplyr' successfully unpacked and MD5 sums checked
package 'curl' successfully unpacked and MD5 sums checked
package 'S4Vectors' successfully unpacked and MD5 sums checked
package 'IRanges' successfully unpacked and MD5 sums checked
package 'GenomicRanges' successfully unpacked and MD5 sums checked
package 'GenomeInfoDb' successfully unpacked and MD5 sums checked
Installing package into 'C:/Users/Neg/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)
installing the source package 'BiocManager'

trying URL 'https://cloud.r-project.org/src/contrib/BiocManager_1.30.25.tar.gz'
Content type 'application/x-gzip' length 593414 bytes (579 KB)
downloaded 579 KB


The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages'
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.12 (BiocManager 1.30.25), R 4.0.2 (2020-06-22)
Installing package(s) 'DESeq2'
Warning: dependency 'locfit' is not available
also installing the dependencies 'cli', 'lifecycle', 'gtable', 'rlang', 'scales', 'vctrs', 'ggplot2'

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cli_3.2.0.zip'
Content type 'application/zip' length 1255499 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rlang_1.0.2.zip'
Content type 'application/zip' length 1718546 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/scales_1.2.0.zip'
Content type 'application/zip' length 616764 bytes (602 KB)
downloaded 602 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/vctrs_0.4.1.zip'
Content type 'application/zip' length 1569486 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/DESeq2_1.30.1.zip'
Content type 'application/zip' length 2863628 bytes (2.7 MB)
downloaded 2.7 MB

Warning: cannot remove prior installation of package 'cli'
Warning: restored 'cli'
Warning: cannot remove prior installation of package 'rlang'
Warning: restored 'rlang'
Warning: cannot remove prior installation of package 'vctrs'
Warning: restored 'vctrs'
installing the source packages 'lifecycle', 'gtable', 'ggplot2'

trying URL 'https://cloud.r-project.org/src/contrib/lifecycle_1.0.4.tar.gz'
Content type 'application/x-gzip' length 107656 bytes (105 KB)
downloaded 105 KB

trying URL 'https://cloud.r-project.org/src/contrib/gtable_0.3.6.tar.gz'
Content type 'application/x-gzip' length 148148 bytes (144 KB)
downloaded 144 KB

trying URL 'https://cloud.r-project.org/src/contrib/ggplot2_3.5.2.tar.gz'
Content type 'application/x-gzip' length 3580451 bytes (3.4 MB)
downloaded 3.4 MB


The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages'
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.0.2/library
  packages:
    boot, class, cluster, codetools, foreign, KernSmooth, lattice, mgcv, nlme,
    nnet, rpart, spatial, survival
Old packages: 'affy', 'affyio', 'annotate', 'AnnotationDbi', 'askpass',
  'backports', 'BH', 'Biobase', 'BiocFileCache', 'BiocGenerics',
  'BiocParallel', 'biomaRt', 'Biostrings', 'bit', 'bit64', 'bitops', 'blob',
  'brio', 'cachem', 'cli', 'colorspace', 'covr', 'cpp11', 'crayon',
  'data.table', 'DBI', 'dbplyr', 'DelayedArray', 'digest', 'evaluate', 'fansi',
  'farver', 'fastmap', 'fontawesome', 'formatR', 'fs', 'gcrma', 'genefilter',
  'generics', 'GenomeInfoDb', 'GenomeInfoDbData', 'GenomicAlignments',
  'GenomicFeatures', 'GenomicRanges', 'glue', 'haven', 'hms', 'htmltools',
  'httr', 'IRanges', 'isoband', 'jsonlite', 'lifecycle', 'limma', 'lubridate',
  'magrittr', 'matrixStats', 'mime', 'openssl', 'org.Hs.eg.db', 'pillar',
  'preprocessCore', 'prettyunits', 'processx', 'progress', 'ps', 'purrr', 'R6',
  'ragg', 'rappdirs', 'Rcpp', 'RcppArmadillo', 'RCurl', 'readr', 'readxl',
  'Rhtslib', 'rlang', 'Rsamtools', 'RSQLite', 'rtracklayer', 'S4Vectors',
  'sass', 'scales', 'simpleaffy', 'snow', 'stringr', 'SummarizedExperiment',
  'sys', 'systemfonts', 'testthat', 'textshaping', 'tibble', 'tidyr',
  'tidyselect', 'timechange', 'tinytex', 'tzdb', 'utf8', 'uuid', 'vctrs',
  'vroom', 'waldo', 'withr', 'xfun', 'XML', 'xml2', 'XVector', 'yaml',
  'zlibbioc'
Warning: packages 'Biobase', 'BiocGenerics', 'DelayedArray', 'GenomeInfoDb', 'GenomicRanges', 'IRanges', 'matrixStats', 'S4Vectors', 'SummarizedExperiment' are in use and will not be installed
also installing the dependencies 'pkgbuild', 'dplyr', 'curl', 'S4Vectors', 'IRanges', 'GenomicRanges', 'GenomeInfoDb', 'memoise', 'BiocGenerics', 'stringi', 'callr', 'pkgload'

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/dplyr_1.0.8.zip'
Content type 'application/zip' length 1382058 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/curl_4.3.2.zip'
Content type 'application/zip' length 4322402 bytes (4.1 MB)
downloaded 4.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/S4Vectors_0.28.1.zip'
Content type 'application/zip' length 2208736 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/IRanges_2.24.1.zip'
Content type 'application/zip' length 2383996 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomicRanges_1.42.0.zip'
Content type 'application/zip' length 2217875 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomeInfoDb_1.26.7.zip'
Content type 'application/zip' length 4129637 bytes (3.9 MB)
downloaded 3.9 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/memoise_2.0.1.zip'
Content type 'application/zip' length 50250 bytes (49 KB)
downloaded 49 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocGenerics_0.36.1.zip'
Content type 'application/zip' length 758698 bytes (740 KB)
downloaded 740 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/stringi_1.7.6.zip'
Content type 'application/zip' length 16449125 bytes (15.7 MB)
downloaded 15.7 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/affy_1.68.0.zip'
Content type 'application/zip' length 1724378 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/affyio_1.60.0.zip'
Content type 'application/zip' length 161513 bytes (157 KB)
downloaded 157 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/annotate_1.68.0.zip'
Content type 'application/zip' length 2230949 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/AnnotationDbi_1.52.0.zip'
Content type 'application/zip' length 5240738 bytes (5.0 MB)
downloaded 5.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/askpass_1.1.zip'
Content type 'application/zip' length 243575 bytes (237 KB)
downloaded 237 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/backports_1.4.1.zip'
Content type 'application/zip' length 110650 bytes (108 KB)
downloaded 108 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocFileCache_1.14.0.zip'
Content type 'application/zip' length 527754 bytes (515 KB)
downloaded 515 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocParallel_1.24.1.zip'
Content type 'application/zip' length 1870917 bytes (1.8 MB)
downloaded 1.8 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/biomaRt_2.46.3.zip'
Content type 'application/zip' length 915291 bytes (893 KB)
downloaded 893 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/Biostrings_2.58.0.zip'
Content type 'application/zip' length 14457520 bytes (13.8 MB)
downloaded 13.8 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bit_4.0.4.zip'
Content type 'application/zip' length 633925 bytes (619 KB)
downloaded 619 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bit64_4.0.5.zip'
Content type 'application/zip' length 564605 bytes (551 KB)
downloaded 551 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bitops_1.0-7.zip'
Content type 'application/zip' length 42425 bytes (41 KB)
downloaded 41 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/brio_1.1.3.zip'
Content type 'application/zip' length 48904 bytes (47 KB)
downloaded 47 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cachem_1.0.6.zip'
Content type 'application/zip' length 78814 bytes (76 KB)
downloaded 76 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cli_3.2.0.zip'
Content type 'application/zip' length 1255499 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/colorspace_2.0-3.zip'
Content type 'application/zip' length 2653870 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/covr_3.5.1.zip'
Content type 'application/zip' length 305699 bytes (298 KB)
downloaded 298 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/data.table_1.14.2.zip'
Content type 'application/zip' length 2600195 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/digest_0.6.29.zip'
Content type 'application/zip' length 266339 bytes (260 KB)
downloaded 260 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/fansi_1.0.3.zip'
Content type 'application/zip' length 365582 bytes (357 KB)
downloaded 357 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/farver_2.1.0.zip'
Content type 'application/zip' length 1751676 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/fastmap_1.1.0.zip'
Content type 'application/zip' length 215436 bytes (210 KB)
downloaded 210 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/fs_1.5.2.zip'
Content type 'application/zip' length 607100 bytes (592 KB)
downloaded 592 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/gcrma_2.62.0.zip'
Content type 'application/zip' length 313262 bytes (305 KB)
downloaded 305 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/genefilter_1.72.1.zip'
Content type 'application/zip' length 1183448 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomicAlignments_1.26.0.zip'
Content type 'application/zip' length 2538126 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomicFeatures_1.42.3.zip'
Content type 'application/zip' length 2387179 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/glue_1.6.2.zip'
Content type 'application/zip' length 171950 bytes (167 KB)
downloaded 167 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/haven_2.5.0.zip'
Content type 'application/zip' length 1315441 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/htmltools_0.5.2.zip'
Content type 'application/zip' length 347438 bytes (339 KB)
downloaded 339 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/isoband_0.2.5.zip'
Content type 'application/zip' length 2726718 bytes (2.6 MB)
downloaded 2.6 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/jsonlite_1.8.0.zip'
Content type 'application/zip' length 1155832 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/limma_3.46.0.zip'
Content type 'application/zip' length 3182293 bytes (3.0 MB)
downloaded 3.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/lubridate_1.8.0.zip'
Content type 'application/zip' length 1718455 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/magrittr_2.0.3.zip'
Content type 'application/zip' length 238095 bytes (232 KB)
downloaded 232 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/mime_0.12.zip'
Content type 'application/zip' length 47949 bytes (46 KB)
downloaded 46 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/openssl_2.0.0.zip'
Content type 'application/zip' length 3994702 bytes (3.8 MB)
downloaded 3.8 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/preprocessCore_1.52.1.zip'
Content type 'application/zip' length 251950 bytes (246 KB)
downloaded 246 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/processx_3.5.3.zip'
Content type 'application/zip' length 1251075 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/ps_1.6.0.zip'
Content type 'application/zip' length 775355 bytes (757 KB)
downloaded 757 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/purrr_0.3.4.zip'
Content type 'application/zip' length 429429 bytes (419 KB)
downloaded 419 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/ragg_1.2.2.zip'
Content type 'application/zip' length 2330934 bytes (2.2 MB)
downloaded 2.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rappdirs_0.3.3.zip'
Content type 'application/zip' length 58780 bytes (57 KB)
downloaded 57 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/Rcpp_1.0.8.3.zip'
Content type 'application/zip' length 3354808 bytes (3.2 MB)
downloaded 3.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RcppArmadillo_0.11.0.0.0.zip'
Content type 'application/zip' length 2402910 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RCurl_1.98-1.6.zip'
Content type 'application/zip' length 3072932 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/readr_2.1.2.zip'
Content type 'application/zip' length 1816633 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/readxl_1.4.0.zip'
Content type 'application/zip' length 1662106 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/Rhtslib_1.22.0.zip'
Content type 'application/zip' length 6700368 bytes (6.4 MB)
downloaded 6.4 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rlang_1.0.2.zip'
Content type 'application/zip' length 1718546 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/Rsamtools_2.6.0.zip'
Content type 'application/zip' length 6505209 bytes (6.2 MB)
downloaded 6.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RSQLite_2.2.12.zip'
Content type 'application/zip' length 2566700 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/rtracklayer_1.49.5.zip'
Content type 'application/zip' length 2929936 bytes (2.8 MB)
downloaded 2.8 MB


RInterpreterError: Failed to parse and evaluate line 'install.packages("BiocManager", repos = "https://cloud.r-project.org")\nBiocManager::install("DESeq2", force = TRUE)\n'.
R error message: "Error in unpackPkgZip(foundpkgs[okp, 2L], foundpkgs[okp, 1L], lib, libs_only,  : \n  ERROR: failed to lock directory 'C:\\Users\\Neg\\OneDrive\\Documents\\R\\win-library\\4.0' for modifying\nTry removing 'C:\\Users\\Neg\\OneDrive\\Documents\\R\\win-library\\4.0/00LOCK'"
R stdout:
Installing package into 'C:/Users/Neg/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)
installing the source package 'BiocManager'

trying URL 'https://cloud.r-project.org/src/contrib/BiocManager_1.30.25.tar.gz'
Content type 'application/x-gzip' length 593414 bytes (579 KB)
downloaded 579 KB


The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages'
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.12 (BiocManager 1.30.25), R 4.0.2 (2020-06-22)
Installing package(s) 'DESeq2'
Warning: dependency 'locfit' is not available
also installing the dependencies 'cli', 'lifecycle', 'gtable', 'rlang', 'scales', 'vctrs', 'ggplot2'

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cli_3.2.0.zip'
Content type 'application/zip' length 1255499 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rlang_1.0.2.zip'
Content type 'application/zip' length 1718546 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/scales_1.2.0.zip'
Content type 'application/zip' length 616764 bytes (602 KB)
downloaded 602 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/vctrs_0.4.1.zip'
Content type 'application/zip' length 1569486 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/DESeq2_1.30.1.zip'
Content type 'application/zip' length 2863628 bytes (2.7 MB)
downloaded 2.7 MB

Warning: cannot remove prior installation of package 'cli'
Warning: restored 'cli'
Warning: cannot remove prior installation of package 'rlang'
Warning: restored 'rlang'
Warning: cannot remove prior installation of package 'vctrs'
Warning: restored 'vctrs'
installing the source packages 'lifecycle', 'gtable', 'ggplot2'

trying URL 'https://cloud.r-project.org/src/contrib/lifecycle_1.0.4.tar.gz'
Content type 'application/x-gzip' length 107656 bytes (105 KB)
downloaded 105 KB

trying URL 'https://cloud.r-project.org/src/contrib/gtable_0.3.6.tar.gz'
Content type 'application/x-gzip' length 148148 bytes (144 KB)
downloaded 144 KB

trying URL 'https://cloud.r-project.org/src/contrib/ggplot2_3.5.2.tar.gz'
Content type 'application/x-gzip' length 3580451 bytes (3.4 MB)
downloaded 3.4 MB


The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwxG1Gb\downloaded_packages'
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.0.2/library
  packages:
    boot, class, cluster, codetools, foreign, KernSmooth, lattice, mgcv, nlme,
    nnet, rpart, spatial, survival
Old packages: 'affy', 'affyio', 'annotate', 'AnnotationDbi', 'askpass',
  'backports', 'BH', 'Biobase', 'BiocFileCache', 'BiocGenerics',
  'BiocParallel', 'biomaRt', 'Biostrings', 'bit', 'bit64', 'bitops', 'blob',
  'brio', 'cachem', 'cli', 'colorspace', 'covr', 'cpp11', 'crayon',
  'data.table', 'DBI', 'dbplyr', 'DelayedArray', 'digest', 'evaluate', 'fansi',
  'farver', 'fastmap', 'fontawesome', 'formatR', 'fs', 'gcrma', 'genefilter',
  'generics', 'GenomeInfoDb', 'GenomeInfoDbData', 'GenomicAlignments',
  'GenomicFeatures', 'GenomicRanges', 'glue', 'haven', 'hms', 'htmltools',
  'httr', 'IRanges', 'isoband', 'jsonlite', 'lifecycle', 'limma', 'lubridate',
  'magrittr', 'matrixStats', 'mime', 'openssl', 'org.Hs.eg.db', 'pillar',
  'preprocessCore', 'prettyunits', 'processx', 'progress', 'ps', 'purrr', 'R6',
  'ragg', 'rappdirs', 'Rcpp', 'RcppArmadillo', 'RCurl', 'readr', 'readxl',
  'Rhtslib', 'rlang', 'Rsamtools', 'RSQLite', 'rtracklayer', 'S4Vectors',
  'sass', 'scales', 'simpleaffy', 'snow', 'stringr', 'SummarizedExperiment',
  'sys', 'systemfonts', 'testthat', 'textshaping', 'tibble', 'tidyr',
  'tidyselect', 'timechange', 'tinytex', 'tzdb', 'utf8', 'uuid', 'vctrs',
  'vroom', 'waldo', 'withr', 'xfun', 'XML', 'xml2', 'XVector', 'yaml',
  'zlibbioc'
Warning: packages 'Biobase', 'BiocGenerics', 'DelayedArray', 'GenomeInfoDb', 'GenomicRanges', 'IRanges', 'matrixStats', 'S4Vectors', 'SummarizedExperiment' are in use and will not be installed
also installing the dependencies 'pkgbuild', 'dplyr', 'curl', 'S4Vectors', 'IRanges', 'GenomicRanges', 'GenomeInfoDb', 'memoise', 'BiocGenerics', 'stringi', 'callr', 'pkgload'

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/dplyr_1.0.8.zip'
Content type 'application/zip' length 1382058 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/curl_4.3.2.zip'
Content type 'application/zip' length 4322402 bytes (4.1 MB)
downloaded 4.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/S4Vectors_0.28.1.zip'
Content type 'application/zip' length 2208736 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/IRanges_2.24.1.zip'
Content type 'application/zip' length 2383996 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomicRanges_1.42.0.zip'
Content type 'application/zip' length 2217875 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomeInfoDb_1.26.7.zip'
Content type 'application/zip' length 4129637 bytes (3.9 MB)
downloaded 3.9 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/memoise_2.0.1.zip'
Content type 'application/zip' length 50250 bytes (49 KB)
downloaded 49 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocGenerics_0.36.1.zip'
Content type 'application/zip' length 758698 bytes (740 KB)
downloaded 740 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/stringi_1.7.6.zip'
Content type 'application/zip' length 16449125 bytes (15.7 MB)
downloaded 15.7 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/affy_1.68.0.zip'
Content type 'application/zip' length 1724378 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/affyio_1.60.0.zip'
Content type 'application/zip' length 161513 bytes (157 KB)
downloaded 157 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/annotate_1.68.0.zip'
Content type 'application/zip' length 2230949 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/AnnotationDbi_1.52.0.zip'
Content type 'application/zip' length 5240738 bytes (5.0 MB)
downloaded 5.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/askpass_1.1.zip'
Content type 'application/zip' length 243575 bytes (237 KB)
downloaded 237 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/backports_1.4.1.zip'
Content type 'application/zip' length 110650 bytes (108 KB)
downloaded 108 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocFileCache_1.14.0.zip'
Content type 'application/zip' length 527754 bytes (515 KB)
downloaded 515 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocParallel_1.24.1.zip'
Content type 'application/zip' length 1870917 bytes (1.8 MB)
downloaded 1.8 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/biomaRt_2.46.3.zip'
Content type 'application/zip' length 915291 bytes (893 KB)
downloaded 893 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/Biostrings_2.58.0.zip'
Content type 'application/zip' length 14457520 bytes (13.8 MB)
downloaded 13.8 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bit_4.0.4.zip'
Content type 'application/zip' length 633925 bytes (619 KB)
downloaded 619 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bit64_4.0.5.zip'
Content type 'application/zip' length 564605 bytes (551 KB)
downloaded 551 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bitops_1.0-7.zip'
Content type 'application/zip' length 42425 bytes (41 KB)
downloaded 41 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/brio_1.1.3.zip'
Content type 'application/zip' length 48904 bytes (47 KB)
downloaded 47 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cachem_1.0.6.zip'
Content type 'application/zip' length 78814 bytes (76 KB)
downloaded 76 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cli_3.2.0.zip'
Content type 'application/zip' length 1255499 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/colorspace_2.0-3.zip'
Content type 'application/zip' length 2653870 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/covr_3.5.1.zip'
Content type 'application/zip' length 305699 bytes (298 KB)
downloaded 298 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/data.table_1.14.2.zip'
Content type 'application/zip' length 2600195 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/digest_0.6.29.zip'
Content type 'application/zip' length 266339 bytes (260 KB)
downloaded 260 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/fansi_1.0.3.zip'
Content type 'application/zip' length 365582 bytes (357 KB)
downloaded 357 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/farver_2.1.0.zip'
Content type 'application/zip' length 1751676 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/fastmap_1.1.0.zip'
Content type 'application/zip' length 215436 bytes (210 KB)
downloaded 210 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/fs_1.5.2.zip'
Content type 'application/zip' length 607100 bytes (592 KB)
downloaded 592 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/gcrma_2.62.0.zip'
Content type 'application/zip' length 313262 bytes (305 KB)
downloaded 305 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/genefilter_1.72.1.zip'
Content type 'application/zip' length 1183448 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomicAlignments_1.26.0.zip'
Content type 'application/zip' length 2538126 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomicFeatures_1.42.3.zip'
Content type 'application/zip' length 2387179 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/glue_1.6.2.zip'
Content type 'application/zip' length 171950 bytes (167 KB)
downloaded 167 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/haven_2.5.0.zip'
Content type 'application/zip' length 1315441 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/htmltools_0.5.2.zip'
Content type 'application/zip' length 347438 bytes (339 KB)
downloaded 339 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/isoband_0.2.5.zip'
Content type 'application/zip' length 2726718 bytes (2.6 MB)
downloaded 2.6 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/jsonlite_1.8.0.zip'
Content type 'application/zip' length 1155832 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/limma_3.46.0.zip'
Content type 'application/zip' length 3182293 bytes (3.0 MB)
downloaded 3.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/lubridate_1.8.0.zip'
Content type 'application/zip' length 1718455 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/magrittr_2.0.3.zip'
Content type 'application/zip' length 238095 bytes (232 KB)
downloaded 232 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/mime_0.12.zip'
Content type 'application/zip' length 47949 bytes (46 KB)
downloaded 46 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/openssl_2.0.0.zip'
Content type 'application/zip' length 3994702 bytes (3.8 MB)
downloaded 3.8 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/preprocessCore_1.52.1.zip'
Content type 'application/zip' length 251950 bytes (246 KB)
downloaded 246 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/processx_3.5.3.zip'
Content type 'application/zip' length 1251075 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/ps_1.6.0.zip'
Content type 'application/zip' length 775355 bytes (757 KB)
downloaded 757 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/purrr_0.3.4.zip'
Content type 'application/zip' length 429429 bytes (419 KB)
downloaded 419 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/ragg_1.2.2.zip'
Content type 'application/zip' length 2330934 bytes (2.2 MB)
downloaded 2.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rappdirs_0.3.3.zip'
Content type 'application/zip' length 58780 bytes (57 KB)
downloaded 57 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/Rcpp_1.0.8.3.zip'
Content type 'application/zip' length 3354808 bytes (3.2 MB)
downloaded 3.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RcppArmadillo_0.11.0.0.0.zip'
Content type 'application/zip' length 2402910 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RCurl_1.98-1.6.zip'
Content type 'application/zip' length 3072932 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/readr_2.1.2.zip'
Content type 'application/zip' length 1816633 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/readxl_1.4.0.zip'
Content type 'application/zip' length 1662106 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/Rhtslib_1.22.0.zip'
Content type 'application/zip' length 6700368 bytes (6.4 MB)
downloaded 6.4 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rlang_1.0.2.zip'
Content type 'application/zip' length 1718546 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/Rsamtools_2.6.0.zip'
Content type 'application/zip' length 6505209 bytes (6.2 MB)
downloaded 6.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RSQLite_2.2.12.zip'
Content type 'application/zip' length 2566700 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/rtracklayer_1.49.5.zip'
Content type 'application/zip' length 2929936 bytes (2.8 MB)
downloaded 2.8 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/sass_0.4.1.zip'
Content type 'application/zip' length 3639619 bytes (3.5 MB)
downloaded 3.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/scales_1.2.0.zip'
Content type 'application/zip' length 616764 bytes (602 KB)
downloaded 602 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/simpleaffy_2.66.0.zip'
Content type 'application/zip' length 826388 bytes (807 KB)
downloaded 807 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/snow_0.4-4.zip'
Content type 'application/zip' length 99127 bytes (96 KB)
downloaded 96 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/sys_3.4.zip'
Content type 'application/zip' length 59823 bytes (58 KB)
downloaded 58 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/systemfonts_1.0.4.zip'
Content type 'application/zip' length 2021380 bytes (1.9 MB)
downloaded 1.9 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/testthat_3.1.3.zip'
Content type 'application/zip' length 2559372 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/textshaping_0.3.6.zip'
Content type 'application/zip' length 2167966 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/tibble_3.1.6.zip'
Content type 'application/zip' length 872395 bytes (851 KB)
downloaded 851 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/tidyr_1.2.0.zip'
Content type 'application/zip' length 1114919 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/tidyselect_1.1.2.zip'
Content type 'application/zip' length 206438 bytes (201 KB)
downloaded 201 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/timechange_0.0.2.zip'
Content type 'application/zip' length 968713 bytes (946 KB)
downloaded 946 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/tzdb_0.3.0.zip'
Content type 'application/zip' length 1445749 bytes (1.4 MB)
downloaded 1.4 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/utf8_1.2.2.zip'
Content type 'application/zip' length 209838 bytes (204 KB)
downloaded 204 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/uuid_1.1-0.zip'
Content type 'application/zip' length 69155 bytes (67 KB)
downloaded 67 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/vctrs_0.4.1.zip'
Content type 'application/zip' length 1569486 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/vroom_1.5.7.zip'
Content type 'application/zip' length 2067692 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/xfun_0.30.zip'
Content type 'application/zip' length 398028 bytes (388 KB)
downloaded 388 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/XML_3.99-0.9.zip'
Content type 'application/zip' length 4258084 bytes (4.1 MB)
downloaded 4.1 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/xml2_1.3.3.zip'
Content type 'application/zip' length 2910114 bytes (2.8 MB)
downloaded 2.8 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/XVector_0.30.0.zip'
Content type 'application/zip' length 679452 bytes (663 KB)
downloaded 663 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/yaml_2.3.5.zip'
Content type 'application/zip' length 209714 bytes (204 KB)
downloaded 204 KB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/zlibbioc_1.36.0.zip'
Content type 'application/zip' length 365125 bytes (356 KB)
downloaded 356 KB

Warning: cannot remove prior installation of package 'S4Vectors'
Warning: restored 'S4Vectors'
Warning: cannot remove prior installation of package 'IRanges'
Warning: restored 'IRanges'
Warning: cannot remove prior installation of package 'GenomicRanges'
Warning: restored 'GenomicRanges'
Error in unpackPkgZip(foundpkgs[okp, 2L], foundpkgs[okp, 1L], lib, libs_only,  :
  ERROR: failed to lock directory 'C:\Users\Neg\OneDrive\Documents\R\win-library\4.0' for modifying
Try removing 'C:\Users\Neg\OneDrive\Documents\R\win-library\4.0/00LOCK'
In addition: Warning messages:
1: In install.packages("BiocManager", repos = "https://cloud.r-project.org") :

In [14]:
import rpy2
print(rpy2.__version__)

3.5.17

In [16]:
import rpy2.robjects as robjects
print(robjects.r('R.home()'))

R[write to console]: In addition:
R[write to console]: Warning message:

R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  library 'C:/Users/Neg/R_libs' contains no packages

[1] "C:/Program Files/R/R-4.0.2"

In [18]:
import rpy2.ipython

In [20]:
import sys
print(sys.executable)

C:\Users\Neg\anaconda3\python.exe

In [12]:
import rpy2.robjects.packages as rpackages
from rpy2.robjects.vectors import StrVector

# Ensure BiocManager is installed
utils = rpackages.importr('utils')
utils.chooseCRANmirror(ind=1)  # select the first CRAN mirror

if not rpackages.isinstalled("BiocManager"):
    utils.install_packages("BiocManager")

# Use BiocManager to install DESeq2
biocmanager = rpackages.importr("BiocManager")
biocmanager.install("DESeq2")

R[write to console]: Installing package into 'C:/Users/Neg/R_libs'
(as 'lib' is unspecified)

  There is a binary version available but the source version is later:
             binary  source needs_compilation
BiocManager 1.30.16 1.30.25             FALSE

R[write to console]: installing the source package 'BiocManager'


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/BiocManager_1.30.25.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 593414 bytes (579 KB)

R[write to console]: downloaded 579 KB


R[write to console]:

R[write to console]:
R[write to console]: The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwVZ5RG\downloaded_packages'
R[write to console]:
R[write to console]:

R[write to console]: 'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org

R[write to console]: Bioconductor version 3.12 (BiocManager 1.30.25), R 4.0.2 (2020-06-22)

R[write to console]: Installing package(s) 'BiocVersion', 'DESeq2'

R[write to console]: Warning:
R[write to console]:  dependency 'locfit' is not available

R[write to console]: also installing the dependencies 'fastmap', 'sys', 'bit', 'cachem', 'askpass', 'bitops', 'formatR', 'bit64', 'blob', 'memoise', 'plogr', 'cpp11', 'curl', 'jsonlite', 'mime', 'openssl', 'colorspace', 'utf8', 'RCurl', 'GenomeInfoDbData', 'zlibbioc', 'matrixStats', 'lambda.r', 'futile.options', 'DBI', 'RSQLite', 'XML', 'xtable', 'httr', 'farver', 'labeling', 'munsell', 'R6', 'viridisLite', 'fansi', 'magrittr', 'pillar', 'pkgconfig', 'GenomeInfoDb', 'XVector', 'MatrixGenerics', 'DelayedArray', 'futile.logger', 'snow', 'BH', 'AnnotationDbi', 'annotate', 'RColorBrewer', 'cli', 'glue', 'gtable', 'isoband', 'lifecycle', 'rlang', 'scales', 'tibble', 'vctrs', 'withr', 'S4Vectors', 'IRanges', 'GenomicRanges', 'SummarizedExperiment', 'BiocGenerics', 'Biobase', 'BiocParallel', 'genefilter', 'geneplotter', 'ggplot2', 'Rcpp', 'RcppArmadillo'

  There are binary versions available but the source versions are later:
                  binary    source needs_compilation
fastmap            1.1.0     1.2.0              TRUE
sys                  3.4     3.4.3              TRUE
bit                4.0.4     4.6.0              TRUE
cachem             1.0.6     1.1.0              TRUE
askpass              1.1     1.2.1              TRUE
bitops             1.0-7     1.0-9              TRUE
formatR             1.12      1.14             FALSE
bit64              4.0.5   4.6.0-1              TRUE
blob               1.2.3     1.2.4             FALSE
cpp11              0.4.2     0.5.2             FALSE
curl               4.3.2     6.2.2              TRUE
jsonlite           1.8.0     2.0.0              TRUE
mime                0.12      0.13              TRUE
openssl            2.0.0     2.3.2              TRUE
colorspace         2.0-3     2.1-1              TRUE
utf8               1.2.2     1.2.4              TRUE
RCurl           1.98-1.6 1.98-1.17              TRUE
matrixStats       0.62.0     1.5.0              TRUE
DBI                1.1.2     1.2.3             FALSE
RSQLite           2.2.12     2.3.9              TRUE
XML             3.99-0.9 3.99-0.18              TRUE
httr               1.4.2     1.4.7             FALSE
farver             2.1.0     2.1.2              TRUE
labeling           0.4.2     0.4.3             FALSE
munsell            0.5.0     0.5.1             FALSE
R6                 2.5.1     2.6.1             FALSE
viridisLite        0.4.0     0.4.2             FALSE
fansi              1.0.3     1.0.6              TRUE
pillar             1.7.0    1.10.2             FALSE
BH              1.78.0-0  1.87.0-1             FALSE
cli                3.2.0     3.6.4              TRUE
glue               1.6.2     1.8.0              TRUE
gtable             0.3.0     0.3.6             FALSE
isoband            0.2.5     0.2.7              TRUE
lifecycle          1.0.1     1.0.4             FALSE
rlang              1.0.2     1.1.6              TRUE
scales             1.2.0     1.3.0              TRUE
tibble             3.1.6     3.2.1              TRUE
vctrs              0.4.1     0.6.5              TRUE
withr              2.5.0     3.0.2             FALSE
ggplot2            3.3.5     3.5.2             FALSE
Rcpp             1.0.8.3    1.0.14              TRUE
RcppArmadillo 0.11.0.0.0  14.4.1-1              TRUE

  Binaries will be installed

R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/fastmap_1.1.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 215436 bytes (210 KB)

R[write to console]: downloaded 210 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/sys_3.4.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 59823 bytes (58 KB)

R[write to console]: downloaded 58 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bit_4.0.4.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 633925 bytes (619 KB)

R[write to console]: downloaded 619 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cachem_1.0.6.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 78814 bytes (76 KB)

R[write to console]: downloaded 76 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/askpass_1.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 243575 bytes (237 KB)

R[write to console]: downloaded 237 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bitops_1.0-7.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 42425 bytes (41 KB)

R[write to console]: downloaded 41 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/bit64_4.0.5.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 564605 bytes (551 KB)

R[write to console]: downloaded 551 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/memoise_2.0.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 50250 bytes (49 KB)

R[write to console]: downloaded 49 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/plogr_0.2.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 18863 bytes (18 KB)

R[write to console]: downloaded 18 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/curl_4.3.2.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 4322402 bytes (4.1 MB)

R[write to console]: downloaded 4.1 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/jsonlite_1.8.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 1155832 bytes (1.1 MB)

R[write to console]: downloaded 1.1 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/mime_0.12.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 47949 bytes (46 KB)

R[write to console]: downloaded 46 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/openssl_2.0.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 3994702 bytes (3.8 MB)

R[write to console]: downloaded 3.8 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/colorspace_2.0-3.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2653870 bytes (2.5 MB)

R[write to console]: downloaded 2.5 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/utf8_1.2.2.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 209838 bytes (204 KB)

R[write to console]: downloaded 204 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RCurl_1.98-1.6.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 3072932 bytes (2.9 MB)

R[write to console]: downloaded 2.9 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/zlibbioc_1.36.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 365125 bytes (356 KB)

R[write to console]: downloaded 356 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/matrixStats_0.62.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 594165 bytes (580 KB)

R[write to console]: downloaded 580 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/lambda.r_1.2.4.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 112097 bytes (109 KB)

R[write to console]: downloaded 109 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/futile.options_1.0.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 21104 bytes (20 KB)

R[write to console]: downloaded 20 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RSQLite_2.2.12.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2566700 bytes (2.4 MB)

R[write to console]: downloaded 2.4 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/XML_3.99-0.9.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 4258084 bytes (4.1 MB)

R[write to console]: downloaded 4.1 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/xtable_1.8-4.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 706085 bytes (689 KB)

R[write to console]: downloaded 689 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/farver_2.1.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 1751676 bytes (1.7 MB)

R[write to console]: downloaded 1.7 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/fansi_1.0.3.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 365582 bytes (357 KB)

R[write to console]: downloaded 357 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/magrittr_2.0.3.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 238095 bytes (232 KB)

R[write to console]: downloaded 232 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/pkgconfig_2.0.3.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 22191 bytes (21 KB)

R[write to console]: downloaded 21 KB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomeInfoDb_1.26.7.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 4129637 bytes (3.9 MB)

R[write to console]: downloaded 3.9 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/XVector_0.30.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 679452 bytes (663 KB)

R[write to console]: downloaded 663 KB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/MatrixGenerics_1.2.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 350876 bytes (342 KB)

R[write to console]: downloaded 342 KB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/DelayedArray_0.16.3.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2395115 bytes (2.3 MB)

R[write to console]: downloaded 2.3 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/futile.logger_1.4.3.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 98390 bytes (96 KB)

R[write to console]: downloaded 96 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/snow_0.4-4.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 99127 bytes (96 KB)

R[write to console]: downloaded 96 KB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/AnnotationDbi_1.52.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 5240738 bytes (5.0 MB)

R[write to console]: downloaded 5.0 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/annotate_1.68.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2230949 bytes (2.1 MB)

R[write to console]: downloaded 2.1 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RColorBrewer_1.1-3.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 55798 bytes (54 KB)

R[write to console]: downloaded 54 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/cli_3.2.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 1255499 bytes (1.2 MB)

R[write to console]: downloaded 1.2 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/glue_1.6.2.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 171950 bytes (167 KB)

R[write to console]: downloaded 167 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/isoband_0.2.5.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2726718 bytes (2.6 MB)

R[write to console]: downloaded 2.6 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/rlang_1.0.2.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 1718546 bytes (1.6 MB)

R[write to console]: downloaded 1.6 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/scales_1.2.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 616764 bytes (602 KB)

R[write to console]: downloaded 602 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/tibble_3.1.6.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 872395 bytes (851 KB)

R[write to console]: downloaded 851 KB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/vctrs_0.4.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 1569486 bytes (1.5 MB)

R[write to console]: downloaded 1.5 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/S4Vectors_0.28.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2208736 bytes (2.1 MB)

R[write to console]: downloaded 2.1 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/IRanges_2.24.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2383996 bytes (2.3 MB)

R[write to console]: downloaded 2.3 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/GenomicRanges_1.42.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2217875 bytes (2.1 MB)

R[write to console]: downloaded 2.1 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/SummarizedExperiment_1.20.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2784529 bytes (2.7 MB)

R[write to console]: downloaded 2.7 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocGenerics_0.36.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 758698 bytes (740 KB)

R[write to console]: downloaded 740 KB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/Biobase_2.50.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2420901 bytes (2.3 MB)

R[write to console]: downloaded 2.3 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocParallel_1.24.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 1870917 bytes (1.8 MB)

R[write to console]: downloaded 1.8 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/genefilter_1.72.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 1183448 bytes (1.1 MB)

R[write to console]: downloaded 1.1 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/geneplotter_1.68.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 1586759 bytes (1.5 MB)

R[write to console]: downloaded 1.5 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/Rcpp_1.0.8.3.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 3354808 bytes (3.2 MB)

R[write to console]: downloaded 3.2 MB


R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RcppArmadillo_0.11.0.0.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2402910 bytes (2.3 MB)

R[write to console]: downloaded 2.3 MB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/BiocVersion_3.12.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 8889 bytes

R[write to console]: downloaded 8889 bytes


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/DESeq2_1.30.1.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 2863628 bytes (2.7 MB)

R[write to console]: downloaded 2.7 MB

package 'fastmap' successfully unpacked and MD5 sums checked
package 'sys' successfully unpacked and MD5 sums checked
package 'bit' successfully unpacked and MD5 sums checked
package 'cachem' successfully unpacked and MD5 sums checked
package 'askpass' successfully unpacked and MD5 sums checked
package 'bitops' successfully unpacked and MD5 sums checked
package 'bit64' successfully unpacked and MD5 sums checked
package 'memoise' successfully unpacked and MD5 sums checked
package 'plogr' successfully unpacked and MD5 sums checked
package 'curl' successfully unpacked and MD5 sums checked
package 'jsonlite' successfully unpacked and MD5 sums checked
package 'mime' successfully unpacked and MD5 sums checked
package 'openssl' successfully unpacked and MD5 sums checked
package 'colorspace' successfully unpacked and MD5 sums checked
package 'utf8' successfully unpacked and MD5 sums checked
package 'RCurl' successfully unpacked and MD5 sums checked
package 'zlibbioc' successfully unpacked and MD5 sums checked
package 'matrixStats' successfully unpacked and MD5 sums checked
package 'lambda.r' successfully unpacked and MD5 sums checked
package 'futile.options' successfully unpacked and MD5 sums checked
package 'RSQLite' successfully unpacked and MD5 sums checked
package 'XML' successfully unpacked and MD5 sums checked
package 'xtable' successfully unpacked and MD5 sums checked
package 'farver' successfully unpacked and MD5 sums checked
package 'fansi' successfully unpacked and MD5 sums checked
package 'magrittr' successfully unpacked and MD5 sums checked
package 'pkgconfig' successfully unpacked and MD5 sums checked
package 'GenomeInfoDb' successfully unpacked and MD5 sums checked
package 'XVector' successfully unpacked and MD5 sums checked
package 'MatrixGenerics' successfully unpacked and MD5 sums checked
package 'DelayedArray' successfully unpacked and MD5 sums checked
package 'futile.logger' successfully unpacked and MD5 sums checked
package 'snow' successfully unpacked and MD5 sums checked
package 'AnnotationDbi' successfully unpacked and MD5 sums checked
package 'annotate' successfully unpacked and MD5 sums checked
package 'RColorBrewer' successfully unpacked and MD5 sums checked
package 'cli' successfully unpacked and MD5 sums checked
package 'glue' successfully unpacked and MD5 sums checked
package 'isoband' successfully unpacked and MD5 sums checked
package 'rlang' successfully unpacked and MD5 sums checked
package 'scales' successfully unpacked and MD5 sums checked
package 'tibble' successfully unpacked and MD5 sums checked
package 'vctrs' successfully unpacked and MD5 sums checked
package 'S4Vectors' successfully unpacked and MD5 sums checked
package 'IRanges' successfully unpacked and MD5 sums checked
package 'GenomicRanges' successfully unpacked and MD5 sums checked
package 'SummarizedExperiment' successfully unpacked and MD5 sums checked
package 'BiocGenerics' successfully unpacked and MD5 sums checked
package 'Biobase' successfully unpacked and MD5 sums checked
package 'BiocParallel' successfully unpacked and MD5 sums checked
package 'genefilter' successfully unpacked and MD5 sums checked
package 'geneplotter' successfully unpacked and MD5 sums checked
package 'Rcpp' successfully unpacked and MD5 sums checked
package 'RcppArmadillo' successfully unpacked and MD5 sums checked
package 'BiocVersion' successfully unpacked and MD5 sums checked
package 'DESeq2' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Neg\AppData\Local\Temp\RtmpwVZ5RG\downloaded_packages

R[write to console]: installing the source packages 'formatR', 'blob', 'cpp11', 'GenomeInfoDbData', 'DBI', 'httr', 'labeling', 'munsell', 'R6', 'viridisLite', 'pillar', 'BH', 'gtable', 'lifecycle', 'withr', 'ggplot2'


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/formatR_1.14.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 96077 bytes (93 KB)

R[write to console]: downloaded 93 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/blob_1.2.4.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 10620 bytes (10 KB)

R[write to console]: downloaded 10 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/cpp11_0.5.2.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 291993 bytes (285 KB)

R[write to console]: downloaded 285 KB


R[write to console]: trying URL 'https://bioconductor.org/packages/3.12/data/annotation/src/contrib/GenomeInfoDbData_1.2.4.tar.gz'

R[write to console]: Content type 'application/octet-stream'
R[write to console]:  length 10673545 bytes (10.2 MB)

R[write to console]: downloaded 10.2 MB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/DBI_1.2.3.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 1137307 bytes (1.1 MB)

R[write to console]: downloaded 1.1 MB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/httr_1.4.7.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 118500 bytes (115 KB)

R[write to console]: downloaded 115 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/labeling_0.4.3.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 10167 bytes

R[write to console]: downloaded 10167 bytes


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/munsell_0.5.1.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 182310 bytes (178 KB)

R[write to console]: downloaded 178 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/R6_2.6.1.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 64507 bytes (62 KB)

R[write to console]: downloaded 62 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/viridisLite_0.4.2.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 1267121 bytes (1.2 MB)

R[write to console]: downloaded 1.2 MB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/pillar_1.10.2.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 408422 bytes (398 KB)

R[write to console]: downloaded 398 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/BH_1.87.0-1.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 14335542 bytes (13.7 MB)

R[write to console]: downloaded 13.7 MB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/gtable_0.3.6.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 148148 bytes (144 KB)

R[write to console]: downloaded 144 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/lifecycle_1.0.4.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 107656 bytes (105 KB)

R[write to console]: downloaded 105 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/withr_3.0.2.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 103240 bytes (100 KB)

R[write to console]: downloaded 100 KB


R[write to console]: trying URL 'https://cloud.r-project.org/src/contrib/ggplot2_3.5.2.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 3580451 bytes (3.4 MB)

R[write to console]: downloaded 3.4 MB


R[write to console]:

R[write to console]:
R[write to console]: The downloaded source packages are in
	'C:\Users\Neg\AppData\Local\Temp\RtmpwVZ5RG\downloaded_packages'
R[write to console]:
R[write to console]:

R[write to console]: Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.0.2/library
  packages:
    boot, class, cluster, codetools, foreign, KernSmooth, lattice, mgcv, nlme,
    nnet, rpart, spatial, survival

R[write to console]: Old packages: 'askpass', 'bit', 'bit64', 'bitops', 'cachem', 'cli',
  'colorspace', 'curl', 'fansi', 'farver', 'fastmap', 'glue', 'isoband',
  'jsonlite', 'matrixStats', 'mime', 'openssl', 'Rcpp', 'RcppArmadillo',
  'RCurl', 'rlang', 'RSQLite', 'scales', 'sys', 'tibble', 'utf8', 'vctrs',
  'XML'

Update all/some/none? [a/s/n]:

 n

<rpy2.robjects.vectors.StrVector object at 0x00000218C6FCAED0> [16]
R classes: ('character',)
['BiocVersion', 'DESeq2']

In [14]:
import rpy2.robjects as robjects

# Set the user-writable library path
robjects.r('.libPaths("C:/Users/Neg/R_libs")')

# Confirm the current library paths
print(robjects.r('.libPaths()'))

R[write to console]: In addition:
R[write to console]: Warning messages:

R[write to console]: 1:
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  library 'C:/Users/Neg/R_libs' contains no packages

R[write to console]: 2:
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  library 'C:/Users/Neg/R_libs' contains no packages

R[write to console]: 3:
R[write to console]: In install.packages(...) :
R[write to console]:

R[write to console]:  installation of package 'lifecycle' had non-zero exit status

R[write to console]: 4:
R[write to console]: In install.packages(...) :
R[write to console]:

R[write to console]:  installation of package 'pillar' had non-zero exit status

R[write to console]: 5:
R[write to console]: In install.packages(...) :
R[write to console]:

R[write to console]:  installation of package 'gtable' had non-zero exit status

R[write to console]: 6:
R[write to console]: In install.packages(...) :
R[write to console]:

R[write to console]:  installation of package 'ggplot2' had non-zero exit status

[1] "C:/Users/Neg/R_libs"                "C:/Program Files/R/R-4.0.2/library"